#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config focused_border_color "#91d7e3"
bspc config normal_border_color "#b7bdf8"
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a feh state=floating center=true
xrandr -s 1920x1080x32
feh --bg-fill $HOME/Pictures/wallpapers/bg.jpg
dunst &

picom -b 

$HOME/.config/polybar/launch.sh 
xautolock -time 1 -locker 'betterlockscreen -l' -detectsleep &
